/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as PulseCheckRouteImport } from './routes/pulse-check'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as FindHelpRouteImport } from './routes/find-help'
import { Route as IndexRouteImport } from './routes/index'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseCheckRoute = PulseCheckRouteImport.update({
  id: '/pulse-check',
  path: '/pulse-check',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const FindHelpRoute = FindHelpRouteImport.update({
  id: '/find-help',
  path: '/find-help',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find-help': typeof FindHelpRoute
  '/learn': typeof LearnRoute
  '/pulse-check': typeof PulseCheckRoute
  '/stories': typeof StoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-help': typeof FindHelpRoute
  '/learn': typeof LearnRoute
  '/pulse-check': typeof PulseCheckRoute
  '/stories': typeof StoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/find-help': typeof FindHelpRoute
  '/learn': typeof LearnRoute
  '/pulse-check': typeof PulseCheckRoute
  '/stories': typeof StoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/find-help' | '/learn' | '/pulse-check' | '/stories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/find-help' | '/learn' | '/pulse-check' | '/stories'
  id: '__root__' | '/' | '/find-help' | '/learn' | '/pulse-check' | '/stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindHelpRoute: typeof FindHelpRoute
  LearnRoute: typeof LearnRoute
  PulseCheckRoute: typeof PulseCheckRoute
  StoriesRoute: typeof StoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse-check': {
      id: '/pulse-check'
      path: '/pulse-check'
      fullPath: '/pulse-check'
      preLoaderRoute: typeof PulseCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-help': {
      id: '/find-help'
      path: '/find-help'
      fullPath: '/find-help'
      preLoaderRoute: typeof FindHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindHelpRoute: FindHelpRoute,
  LearnRoute: LearnRoute,
  PulseCheckRoute: PulseCheckRoute,
  StoriesRoute: StoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
