/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PulseCheckRouteImport } from './routes/pulse-check'
import { Route as IndexRouteImport } from './routes/index'

const PulseCheckRoute = PulseCheckRouteImport.update({
  id: '/pulse-check',
  path: '/pulse-check',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pulse-check': typeof PulseCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pulse-check': typeof PulseCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pulse-check': typeof PulseCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pulse-check'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pulse-check'
  id: '__root__' | '/' | '/pulse-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PulseCheckRoute: typeof PulseCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pulse-check': {
      id: '/pulse-check'
      path: '/pulse-check'
      fullPath: '/pulse-check'
      preLoaderRoute: typeof PulseCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PulseCheckRoute: PulseCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
